glossar:
  css:
    maxWidth: 450
    maxHeight: 300
  illegal: "<"
  templates: 
    - ce_glossar
    - glossar_default
    - glossar_error
    - glossar_layer
  tables: 
    - tl_settings
    - tl_sw_glossar
    - tl_content
    - tl_page
    - tl_glossar
    - tl_news_archive
    - tl_faq_category
    - tl_calendar